---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foldingathome-config
data:
  config.xml: |
    <config>

      <!-- Allow Remote -->
      <allow v='127.0.0.1 0.0.0.0/0'/>
      <web-allow v='127.0.0.1 0.0.0.0/0'/>
      <command-allow-no-pass v='127.0.0.1 0.0.0.0/0'/>

      <!-- User Information -->
      <passkey v=''/>
      <team v=''/>
      <user v=''/>

      <!-- Slot Control -->
      <power v='full'/>

      <!-- Folding Slots -->
      <slot id='0' type='SMP'> <cpus v='2'/> </slot>

    </config>
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fah
  labels:
    app: fah
spec:
  serviceName: fah-sts
  replicas: 2
  selector:
    matchLabels:
      app: fah
  template:
    metadata:
      labels:
        app: fah
    spec:
      containers:
        - name: fah-sidecar
          ports:
            - containerPort: 80
              name: healthz
          image: ghcr.io/ebiiim/fah-sidecar:1.1.0
          command:
            - "./main"
            - "-nodename"
            - "-interval"
            - "1.0s"
            - "$(NODE_NAME)"
            - "http://fahc"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
        - name: fah-app
          image: "foldingathome/fah-gpu:latest"
          command:
            - "/usr/bin/FAHClient"
            - "--config"
            - "/fah/config.xml"
            - "--config-rotate=false"
            - "--run-as"
            - "1234"
            - "--pid-file=/fah/fahclient.pid"
            - "--client-threads=2"
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1234
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /fah/
              name: fahclient
      volumes:
        - name: fah-app-config
          configMap:
            name: foldingathome-config
      initContainers:
        - name: copy-config
          imagePullPolicy: Always
          image: "foldingathome/fah-gpu:latest"
          command:
            - "cp"
            - "/fahcfg/config.xml"
            - "/fah/config.xml"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1234
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: fahclient
              mountPath: /fah/
            - name: fah-app-config
              mountPath: /fahcfg
  volumeClaimTemplates:
    - metadata:
        name: fahclient
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
